#channels:
#  - conda-forge
dependencies:
  - python>=3.5
  - sphinx>=1.4
  - pip
  - pandoc
  - nbconvert
  - ipykernel
  - pip:
    - git+git://github.com/mgeier/nbsphinx.git@pygments-background
    - sphinx-nbexamples
    - sphinx-gallery
