name: Run README

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Run README
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install https://github.com/DominiqueMakowski/popularipy/zipball/master
        cd $GITHUB_WORKSPACE
        python setup.py install 
   
    - name: Run README_examples.py
      run: |
        cd $GITHUB_WORKSPACE/docs/readme
        python README_examples.py
        git add features.png
        git add README_complexity_optimize.png
        git add README_ecg.png
        git add README_eda.png
        git add README_embedding.png
        git add README_emg.png
        git add README_hdi.png
        git add README_popularity.png
        git add README_rsp.png
        git add README_signalprocessing.png
        git add README_simulation.png
        git add workflow.png
        
    - name: Create pull request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update README graphs
          title: 'Update README graphs'
          branch: update-graphs
        