name: Tests

# on: [push, pull_request]
on: pull_request

jobs:
  build:
    name: Tests
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 4
      matrix:
        # https://help.github.com/articles/virtual-environments-for-github-actions
        platform:
          - ubuntu-16.04
          - ubuntu-latest  # ubuntu-18.04
          - macos-latest  # macOS-10.14
          - windows-latest  # windows-2019
        python-version: [3.7, 3.8]
        #exclude:
        #  - platform: windows-latest
        #    python-version: 3.8

    steps:
    - uses: actions/checkout@master
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools pip wheel
        python -m pip install tox-gh-actions
        tox
        
    - name: Test with pytest
      run: |
        # Install test deps
        pip install numpy
        pip install pandas
        pip install scipy
        pip install sklearn
        pip install matplotlib
        pip install bioread
        pip install mne
        pip install pyentrp
        pip install nolds
        pip install biosppy
        pip install PyWavelets
        
        # Install problematic packages
        #pip install conda
        #conda install -c conda-forge cvxopt
        pip install cvxopt
        
        # Test
        pip install pytest
        python setup.py install
        tox
        pytest
